// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Suncity.Web.Context;

namespace suncity.web.Migrations
{
    [DbContext(typeof(SuncityContext))]
    [Migration("20190928085903_updateQustionnaire")]
    partial class updateQustionnaire
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Suncity.Web.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressRegistration");

                    b.Property<string>("AddressResidence");

                    b.Property<string>("BirthDate");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("IsRussianCitizenship");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Surname");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Suncity.Web.Models.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalComment");

                    b.Property<string>("AssessTheMoodOfTheChildBeforeAndAfterTheMeeting");

                    b.Property<Guid?>("ChildId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("DescribeYourMoodAfterTheMeeting");

                    b.Property<int>("Duration");

                    b.Property<Guid?>("MentorId");

                    b.Property<string>("Questions");

                    b.Property<bool>("Status");

                    b.Property<string>("TargetForNextMeeting");

                    b.Property<string>("WhatDidYouEndUpDoing");

                    b.Property<string>("WhatDidYouPlanToDoAtTheMeeting");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("MentorId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("suncity.web.Models.User.SunCityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<DateTime>("LastLogon");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<DateTime>("Registered");

                    b.Property<string>("Surname");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Suncity.Web.Models.Report", b =>
                {
                    b.HasOne("suncity.web.Models.User.SunCityUser", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId");

                    b.HasOne("suncity.web.Models.User.SunCityUser", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId");
                });
#pragma warning restore 612, 618
        }
    }
}
